github/learning-lab-components

README.md

Closes #55
Adding a version badge to the README, which looks basically like this:

Add version badge to README

---

actions/getFileContents/index.js
actions/getFileContents/index.test.js

If a course author calls `getFileContents`, but the file doesn't exist, the action errors out. We therefore can't use it to `gate` information.
Basically wrapped the `getBlob` call in a `try`/`catch`.
---

getFileContents action: Fail gracefully if file does not exist

---

README.md

The codecov badge added by PR #34 from badgen.net appears to have a 3-hour cache time for proxies (like GitHub's camo cache for images in Markdown files 😢) via the `s-maxage` value in its `Cache-Control` HTTP response header.
The equivalent badge from the shields.io only has a cache time of 2 minutes via the `max-age` value in its `Cache-Control` HTTP response header, which is much more useful for badges.
Switch service for the codecov badge in README. 🛡

Switch codecov badge service in README

---

README.md

To help bolster contributor and consumer confidence in our dependency management, this adds proof that our repo is enabled for Dependabot support. 🤖 
Add a Dependabot badge to the README

Add Dependabot enablement badge to README

---

README.md

To help us keep track of our dependencies' currentness. Combined with Dependabot, hopefully these will never get too outdated for long. 🤞 
Add currentness status badges for our package's `dependencies` and `devDependencies` to the README.

Add DavidDM dependency status badges to README

---

README.md

Now that I have a better understanding of the GPR UI, I realized that I could have a more direct link to the latest version of our published package.
Point to the specific package's page in GPR from the README

Update README to use direct link to latest package

---

actions/assignRegistrant/schema.js
actions/closeIssue/schema.js
actions/createPullRequestComment/schema.js
actions/createReview/schema.js
actions/createStatus/schema.js
actions/gate/schema.js
actions/getIssue/schema.js
actions/getPullRequest/schema.js
actions/mergePullRequest/schema.js
actions/requestReviewFromRegistrant/schema.js
actions/respond/schema.js

Follow-on to issues discovered while trying to integrate #69 into GitHub Learning Lab
Joi also changed the API expectations for the `Joi.alternatives()` method. 😮

Update Joi.alternatives usage for 16.x compatibility

---

README.md

If an image in a Markdown file does not have an explicit link around it, GitHub adds a link to the image itself. All of our badges except for the Dependabot badge have an explicit link wrapping, so adding this gives us more consistency between badges.
- Add a more useful link around the Dependabot badge
- Update a few link URLs to be absolute if they might fail based on how someone is viewing the `README.md`

Add a more useful link around the Dependabot badge

---

.github/ISSUE_TEMPLATE/blank.md

When I added the "Blank Issue" issue template (in #36), I was copying that idea from another repo's issue templates. I also did not notice this handy link that achieves exactly the same thing:
Removing the "Blank Issue" template.

Delete the Blank Issue template

---

.github/workflows/ci_build.yml
.github/workflows/release_management.yml

Currently, publishing an NPM package to the GitHub Package Registry will automatically create a new Git Tag and GitHub Release for the new version unless they have already been published beforehand.
In combination with Release Drafter, which is continuously building up a Draft Release for the next release, the GPR publication ignores the Draft Release and creates its own, thereby requiring us to retroactively update the GPR-created Release's contents with the Draft Release's content. This is silly and annoying, so I made a new Action called `node-draft-releaser` to disrupt this process with automation. 🤖 🎉 
Adding a new workflow called "Release Management" containing 3 jobs [that run on a push to `master`], with dependencies on each other (`needs:`) and therefore run sequentially:
1. Run …

Actions workflow: Release Management

---

actions/createStatus/__snapshots__/index.test.js.snap
actions/createStatus/index.js
actions/createStatus/index.test.js

There's a bug in `createStatus` that does't send through the expected state when it's specified by the author. The status is returned from GitHub with `state: pending`.
This was also brought up in https://github.com/github/learning-lab-components/pull/97#issuecomment-532998584. 
There was a missing `else` in the conditional where we parse through the parameters for a `createStatus` action.
❤️ thanks to @JasonEtco for helping me with this
---

Fix createStatus when using an expected state

---

.github/workflows/release_management.yml

Adds some extra verification to ensure that our release management workflow continues to be valid in the future even if we change the other pieces.
Adds another [ordered] Job to the Release Management workflow to validate the GitHub Release and the `"package.json"` file against a handful of semantic versioning rules.

Add validate-semver-release action to Release Management workflow

---

actions/createStatus/README.md
actions/createStatus/schema.js
package-lock.json

With the `createStatus` action, `pending`, `failure`, and `success` can be their own field as well as the options for the `state` field. The current documentation is clear about those as their own fields, but unclear about what the possible options are for the `state` field. 
Documentation
---
- ~~Added or updated tests, and verified they pass by executing `npm test`~~
- ~~Added or updated code comments, if applicable~~
- ~~Generated up-to-date documentation by executing `npm run doc`, if a schema was added or updated~~

createStatus docs: Include possible "state" fields

---

actions/README.md

While adding a new action today, I had some failing tests as a result of not updating the snapshots. 
This PR adds a note to the README to instruct users update the snapshots.
---

Add instruction to update snapshots

---

actions/README.md
actions/enablePages/README.md
actions/enablePages/index.js
actions/enablePages/index.test.js
actions/enablePages/schema.js
tests/actions/__snapshots__/index.test.js.snap

Learning Lab courses often use GitHub Pages as a way to give the user immediate feedback on their changes. However, the process of enabling pages requires navigation to settings and then back. A new endpoint was added to the GitHub API to enable pages on behalf of the user. This action takes advantage of this endpoint to improve the user experience.
Adds a new action to enable GitHub Pages on the learner's repository:
```
type: enablePages
```
By default, the action will enable pages on master, however it also accepts the optional branch of `gh-pages` or path of `/docs`.
:sparkles: and :tada: to @JasonEtco for walking me through this process!
---

add new action to enable GitHub Pages

---

.github/workflows/release_management.yml

Upon the first release made after [adding the `validate-semver-release` Action in our Release Management workflow](#108), we now see/realize that the Action was created specifically to execute on a `release` event.
Due to the limitation of the results of one workflow (i.e. creating a Release) made with the `GITHUB_TOKEN` not being allow to trigger another workflow for rough prevention of infinite loops, we are currently attempting to use this Action on a `push` event instead.
Our misuse is currently [causing our Release Management workflow to fail](https://github.com/github/learning-lab-components/runs/519675150):
At least for now, we need to remove the use of the `validate-semver-release` Action. 😢

Remove validate-semver-release action from Release Management workflow

---

actions/README.md
actions/reopenIssue/README.md
actions/reopenIssue/__snapshots__/index.test.js.snap
actions/reopenIssue/index.js
actions/reopenIssue/index.test.js
actions/reopenIssue/schema.js
tests/actions/__snapshots__/index.test.js.snap

Fulfills a need we encountered while authoring a new internal course while avoiding using the `octokit` action directly.
- Created a new `reopenIssue` bot action
- It will reopen a closed issue/PR
- It will not negatively affect an open issue/PR
- It will fail for a non-existent issue
---

Create new 'reopenIssue' bot action

---

.github/CONTRIBUTING.md

The release instructions are now out-of-date as we automated some of the process with GitHub Actions! 🎉 
Update the release instructions documentation.

Update instructions for releasing a new version

---

actions/createIssue/README.md
actions/createIssue/__snapshots__/index.test.js.snap
actions/createIssue/index.js
actions/createIssue/index.test.js
actions/createIssue/schema.js

We are currently unable to create an issue and supply labels. Actually, we don't have any way of applying labels. This just updates the createIssue action to allow this option.
We're currently doing this [with Octokit](https://github.com/githubtraining/write-github-script/blob/3396a674484501dd49d522d333af182930a6c59a/config.yml#L373-L387)
Adds a `labels` option (an array) to the `createIssue` action.
---

Allow labels option for createIssue

---

actions/enablePages/index.js
actions/enablePages/index.test.js

Closes #156 
This fixes the preview header used in the `enablePages` action, according to the [API docs](https://developer.github.com/v3/repos/pages/#enable-a-pages-site).
---

Fix enablePages preview header

---

actions/createFile/README.md
actions/createFile/schema.js
actions/createPullRequest/README.md
actions/createPullRequest/__snapshots__/index.test.js.snap
actions/createPullRequest/index.js
actions/createPullRequest/schema.js
actions/enablePages/README.md
actions/enablePages/index.js
actions/enablePages/index.test.js
actions/enablePages/schema.js
actions/getTree/README.md
actions/getTree/index.js
actions/getTree/schema.js
actions/mergeBranch/README.md
actions/mergeBranch/__snapshots__/index.test.js.snap
actions/mergeBranch/index.js
actions/mergeBranch/index.test.js
actions/mergeBranch/schema.js
actions/removeBranchProtection/README.md
actions/removeBranchProtection/__snapshots__/index.test.js.snap
actions/removeBranchProtection/index.js
actions/removeBranchProtection/index.test.js
actions/removeBranchProtection/schema.js
actions/updateBranchProtection/README.md
actions/updateBranchProtection/__snapshots__/index.test.js.snap
actions/updateBranchProtection/index.js
actions/updateBranchProtection/index.test.js
actions/updateBranchProtection/schema.js
helpers/get-default-branch.js
tests/mockContext.js

Because of an internal work item to change the default name of the default branch on all new repositories. This code needs to be flexible around the default branch's name.
Every time we assume `master` is the default branch, we now check `context.payload.repository.default_branch` (via a `getDefaultBranch` helper). I've updated all the docs, snapshots and code comments!
---

Use the default branch instead of hard-coding master

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/release_management.yml
actions/README.md

We recently renamed our default branch from `master` to `main` to have more inclusive language.
I renamed the `master` branch to `main`, updated the default branch setting, updated the branch protection settings, retargeted the open PRs, and deleted the `master` branch. _Finally,_ I created this PR to update our documentation and CI configuration to reflect that new branch name.

Update docs and CI to refer to 'main' as the default branch
